home-assistant-ecosystem/home-assistant-cli

- homeassistant_cli/helper.py
This unbreaks `hass-cli info` (the returned component list is a set).
> add a custom jsonencoder to avoid breaking on sets

- homeassistant_cli/plugins/service.py
Querying works as follows:
* When no domain is given, lists all services from all domains
* When a domain is given, lists all services available in that domain
* Passing verbose mode will print out usage (incl. fields and examples)
Calling is also straightforward:
$ hass-cli service light turn_off '{"entity_id": "light.my_shiny_light"}'
> Add service plugin for querying and calling services

- homeassistant_cli/cli.py
- homeassistant_cli/config.py
- homeassistant_cli/remote.py
Why:
* users setting up hass or hass.io might enable signed certificates
and when they do hass-cli would fail to connect due to default
SSL validation.
* introduce --insecure flag which will disable SSL verificaiton
(but not hostname verfication) to allow use of self-signed certs.
Fixes #8
> Add --insecure flag to allow self-signed certs

- homeassistant_cli/cli.py
- homeassistant_cli/const.py
- tests/test_defaults.py
Why:
* would be nice if you are using standard HASSIO_TOKEN that we will
default to hassio.local server instead of localhost
* As suggested in #23 we'll use hassio.local if HASSIO_TOKEN is
available and no HASS_TOKEN active.
> Hass.io compatibility #23

- pyproject.toml
- setup.py
Why:
* getting really tired of manually formatting python code before commit
* add black in test dependencies similar to flake8
* add pyproject.toml as black only supports that format
* black was chosen as it seem to be the one of the formatters
that actually is consistent and most "pythonic"
* did disable its autoformatting of quotes as otherwise
it would radically change/break with homeassistant formatting
* note: you'll need to run black manually or enable in your
editor like vscode.
> Add black for formatting

- .pre-commit-config.yaml
Why:
* precommits are helpful but hard to remember/configure right
* adds .pre-commit-config.yaml which enables isort, flake8 and black
formatting.
* To use it see details at https://pre-commit.com
but for trivial cases its:
````
pip install pre-commit
pre-commit install
```
after that on commit the precommit linters will be run and if any
failure or updates done the commit will fail.
Check the failures and edits done - once happy commit again.
> Add precommit configuration

- homeassistant_cli/autocompletion.py
- homeassistant_cli/helper.py
- homeassistant_cli/plugins/entity.py
- homeassistant_cli/plugins/service.py
- homeassistant_cli/remote.py
- tests/test_plugins.py
- tests/test_service.py
Why:
* want to call services
* adds `service call` allowing you to do things like:
`hass-cli -v service call homeassistant.toggle --arguments entity_id=light.office_light`
* adds `service list` to get list of services if you do:
`hass-cli service list`
but you can also use filters:
`hass-cli service list 'turn_on'`
will only return the services that have `turn_on` somewere in their name
Its a regular expresion so you can go crazy if you want:
`hass-cli service list 'homeassistant\..*turn`
> Add `service` plugin

- homeassistant_cli/cli.py
- homeassistant_cli/config.py
- homeassistant_cli/const.py
- homeassistant_cli/helper.py
- homeassistant_cli/plugins/entity.py
- homeassistant_cli/plugins/event.py
- homeassistant_cli/plugins/info.py
- homeassistant_cli/plugins/raw.py
- homeassistant_cli/plugins/service.py
- homeassistant_cli/plugins/template.py
- setup.py
example:
```
hass-cli --output=table entity toggle light.office_light                                             
ENTITY                          DESCRIPTION    STATE
------------------------------  -------------  -------
group.office_lights_motionview  office lights  on
light.office_light              Office Light   on
```
see more details in commit msgs.
> Fixing piping and adding support for output=table

- homeassistant_cli/cli.py
- homeassistant_cli/config.py
Why:
* printing exception backtraces aren't really part of what verbose
does. Sometimes you want verbose/additional info but not dumping
of exceptions on "expected" errors - like timeouts.
* add a -x flag.
> Introduce -x flag for showing exceptions

- homeassistant_cli/hassconst.py
- homeassistant_cli/remote.py
- setup.py
Why:
* we only use the .const.py from hass thus its overkill wanting
the full dependency chain.
* copy homeassistant.const.py from core to hass-cli
> Remove dependency on homeassistant core

- homeassistant_cli/remote.py
- setup.py
Why:
* aiohttp was just used for a few headers.
* might need it back later for ws integration, but for now its
just "noise"
* remove the aiohttp dependency
> Remove bogus aiohttp dependency

- MANIFEST.in
Otherwise, installing from source fails with `error: [Errno 2] No such file or directory: 'LICENSE.md'`.
> Include LICENSE.md in PyPI tarball

- homeassistant_cli/cli.py
- homeassistant_cli/config.py
- homeassistant_cli/remote.py
shared session works, but not (yet) able to test client certificates.
Please try use this by using this pullrequest and run:
`hass-cli --cert <path.to.pem> info`
and see if it lets you connect.
If not, run again with `-x --debug` flags and paste the content here (
do mask out tokens/pem content before!)
> WIP: Add shared session + client certificates.

- homeassistant_cli/plugins/edit.py
- homeassistant_cli/remote.py
- tests/test_defaults.py
- tests/test_info.py
In #64 it was found that `hass-cli info` would return empty result
when there was 401 auth errors AND for some reason setting HASSIO_TOKEN was not
enough to make use of http://hassio/homeassistant as base url.
401 was easy fix by simply ensuring we will throw
an exception if error occurs + added basic test for this.
Hassio issue was because urljoin was used for combing baseurl with api
path. Now moved to basic string concat so it will work as expected, i.e.
http://hassio/homeassistant + /api/discovery_info gives http://hassio/homeassistant/api/discovery_info
And not http://hassio/api/discovery_info which was the cause of the bugs.
> WIP: Fix bad url creation and don't ignore 401

- homeassistant_cli/autocompletion.py
- homeassistant_cli/cli.py
- homeassistant_cli/config.py
- homeassistant_cli/remote.py
- tests/test_defaults.py
I was not sure if it was right thing to add `HASSIO_PASSWORD` .
Should I add tests for this functionality?
> Add --password flag for providing API password

- .gitignore
- homeassistant_cli/autocompletion.py
- homeassistant_cli/cli.py
- homeassistant_cli/config.py
- homeassistant_cli/const.py
- homeassistant_cli/remote.py
- tests/test_defaults.py
Why:
* when getting started it would be helpful to locate running HA
servers on local network.
* introduce `auto` for server option to activate automatic configuration
of the server/base url.
* when `auto` presence of HASSIO_TOKEN will make it use hassio default
url otherwise use zeroconf to lookup HA on local network.
Fixes #77
> feat: add server=auto now uses zeroconf to find HA

- homeassistant_cli/config.py
Why:
* last commit broke autocompletion when server=auto
* actually use detected server.
Fixes #77
> bug: fix auto when doing autocomplete

- .travis.yml
- script/check_release
- script/release
Why:
* I don't trust myself in deploying things right all the time.
* do an initial setup that automatically deploy to testpypi when
master is tagged, build passed and check_release passes.
* when verified to work we can move it to deploy properly to pypi
> Add testpypi to master tagged builds

- .pre-commit-config.yaml
- homeassistant_cli/autocompletion.py
- homeassistant_cli/cli.py
- homeassistant_cli/plugins/entity.py
- homeassistant_cli/plugins/service.py
- homeassistant_cli/remote.py
- tests/test_defaults.py
Why:
* list always return everything which gets quite massive.
* add `entity list <filter>` support via regular expression.
Similar to what `service list <filter>` does.
* Also added mypy to precommit hook setup
Fixes #38
> feat(entity): entity list regular filtering

- homeassistant_cli/autocompletion.py
- homeassistant_cli/plugins/raw.py
- setup.cfg
- tests/test_completion.py
- tests/test_raw.py
Why:
* tired of looking up comon api methods
* simple 'hack' that will populate completion with the api strings
found in hassconst.py. Its a nice start.
> autocomplete for raw api

- homeassistant_cli/cli.py
- homeassistant_cli/config.py
- homeassistant_cli/const.py
- homeassistant_cli/helper.py
- homeassistant_cli/plugins/config.py
- homeassistant_cli/plugins/entity.py
- homeassistant_cli/plugins/info.py
- homeassistant_cli/plugins/raw.py
- homeassistant_cli/plugins/service.py
- tests/test_entity.py
- tests/test_event.py
- tests/test_info.py
- tests/test_raw.py
- tests/test_service.py
Why:
* Not all commands looks better in table format
* Not all commands looks great in json/yaml format
* introduce `auto` format so command/groups can define what they want
* make entity and other commands use `table` for better look AND
more like a command line tool for use in pipes.
* Fix all tests so they are more explict about what format they
expect.
> Introduce format=`auto`

- homeassistant_cli/plugins/entity.py
Why:
* annoying getting N outputs when 1 is sufficent
* just pass entities array to `entity_id` instead of cmd per each entity
> Bulk update entities in toggle, turn_on & turn_off

- homeassistant_cli/helper.py
- homeassistant_cli/plugins/entity.py
- homeassistant_cli/remote.py
Why:
* looking in hass source code i noticed /period actually support
taking a comma separated list.
* can now pass in multiple entities for `history`, ex.
`hass-cli entity history light.kitchen binary_sensor.kitchenmotion`
> Multiple entities for history period

- homeassistant_cli/config.py
- homeassistant_cli/helper.py
- homeassistant_cli/plugins/entity.py
- homeassistant_cli/plugins/event.py
- homeassistant_cli/plugins/template.py
- homeassistant_cli/yaml.py
- setup.py
- tests/test_info.py
Why:
* using two libraries for yaml is annoying.
* 0.4 accidentally used pyyaml incompatible with homeassistant so
lets avoid that.
* move all code to use ruamel yaml.
* made it possible eventually to control what version of yaml
ruamel will use if ever needed.
> Remove pyaml and move to ruamel only for yaml

- homeassistant_cli/autocompletion.py
- homeassistant_cli/hassconst.py
- homeassistant_cli/plugins/area.py
- homeassistant_cli/plugins/device.py
- homeassistant_cli/plugins/event.py
- homeassistant_cli/remote.py
- homeassistant_cli/yaml.py
- setup.py
- tests/fixtures/default_areas.json
- tests/fixtures/default_devices.json
- tests/test_area.py
- tests/test_completion.py
- tests/test_device.py
- tests/test_plugins.py
- tox.ini
Why:
* HA is exposing more and more functionallity tied to Device and
Area registries. Nice to be able to edit areas especially without
requiring use of browser UI.
* Monitoring events can be tedious. Lets have a way to monitor.
* add initial basic support of access websocket api.
Currently no sharing of connection. One connection
made per request, similar to rest api.
* Add `device list` and `assign` command for devices.
- list takes a match/filter similar to `entity list`
i.e. `hass-cli device list 'Kitchen.*Light'
- assign takes an area name or id together with
one or more devices specificed by id/name or match.
i.e. `device assign "Kitchen" --match "Kitchen" 'Ceiling Lamp' 32342334
* Autocompletion for area names.
* fixes for setuptools bug that cause …
> WIP: Device, Area and event support

- homeassistant_cli/cli.py
Add env vars to the output of `--help`.
@lmamakos, were you thinking about something like that?
**Related issue:** fixes #173
> Update help output (fixes #173)

- homeassistant_cli/plugins/system.py
- homeassistant_cli/remote.py
Add support for the [System health](https://www.home-assistant.io/components/system_health/) component.
```bash
$ hass-cli system health
{'id': 1, 'type': 'result', 'success': True, 'result': {'homeassistant': {'version': '0.88.0.dev0', 'dev': True, 'hassio': False, 'virtualenv': True, 'python_version': '3.7.2', 'docker': False, 'arch': 'x86_64', 'timezone': 'Europe/Zurich', 'os_name': 'Linux'}, 'lovelace': {'mode': 'storage', 'resources': 0, 'views': 2}}}
```
> Add support for system health

- homeassistant_cli/const.py
- homeassistant_cli/helper.py
- homeassistant_cli/plugins/event.py
- homeassistant_cli/remote.py
Why:
* event watch is dumping Dict rather than json
* event watch is not honoring output formats
* add callback mechanism for websocket calls
* used usual formatter for every message
Means event watch dumps 1 table per msg.
Recommended to use --no-headers
* Made formatting just dump one item when output
is not actually a list.
* Only print `event` messages
> fix: event watch has reliable json output

- homeassistant_cli/plugins/map.py
- tests/test_map.py
Why:
* openstreetmap isn't always the best option.
* there are more than just configuration with location info.
* introduce a `--service` option to let you choose which
map service to use. currently: openstreetmap, google and bing
implemented
* add optional entity parameter to lookup and it has
latitiude and longitude in its state it will be mapped.
* bing has extra feature of allowing showing a name/label, here
`friendly_name` is used otherwise `entity_id`
Future idea: allow to map multiple points, can be done as directions
in google but Bing has better support.
> feat: `map` for entities and multiple map services

- README.rst
The PR for adding this as a formula in homebrew is not yet reviewed nor merged, so I would suggest holding off on this PR until that is complete (it's my first homebrew submission, so I may need to make updates there).
For homebrew users (ie OSX only) all that would be required to install is:
`brew install hass-cli`
Further updates would be automatic for end users via the usual `brew upgrade` process. New hass-cli releases require updates to the formula.
Request issue: #146 
Formula PR: https://github.com/Homebrew/homebrew-core/pull/36915
> Add instructions for homebrew installation

- .circleci/config.yml
- .travis.yml
- homeassistant_cli/autocompletion.py
- homeassistant_cli/config.py
- homeassistant_cli/plugins/raw.py
- homeassistant_cli/yaml.py
- setup.cfg
- setup.py
- tests/test_raw.py
- tox.ini
Why:
* testing out websocket apis before there are commands for it
are tedious. would be nice to have ability like `raw get` to
access websocket api.
* introduce `hass-cli raw ws <method> --json <optional data>` command.
Example:
```
hass-cli raw ws config/area_registry/delete --json='{ "area_id":"2c8bf93c8082492f99c989896962f207" }'
```
Resolves:
> feat(plugin): hass-cli raw ws for websocket apis

- homeassistant_cli/plugins/event.py
- homeassistant_cli/remote.py
Currently if an auth error occurs (e.g. if one has not configured any auth info at all on command line or env), commands just exit with successful exit status without outputting anything. This makes them blow up visibly.
> Raise HomeAssistantCliError on auth errors

- README.rst
- homeassistant_cli/cli.py
- homeassistant_cli/helper.py
Hello!
I found myself wanting to run something like `hass-cli event watch | grep ... | jq ...` and it was more complicated than I would have liked because of the format, so I added a flag to allow [ndjson](http://ndjson.org/) as an output format, which makes things like that much easier...
> Support `--output ndjson`

- homeassistant_cli/plugins/area.py
- homeassistant_cli/plugins/device.py
I was looking at the device list and seeing the area ids seemed not so useful so I changed it to show the area name instead. I haven't done a lot of python so if there's a more idiomatic way to do this I'm happy to change it. 😄
> show area name instead of id on device list

- homeassistant_cli/hassconst.py
- homeassistant_cli/plugins/state.py
Fix error with state history, eg
```
hass-cli --server=http://homeassistant:8123 --sort-by last_changed -l DEBUG state history --since 50m group.g_present
```
Fixes #332 - `list` function shadows built-in python version
> prevent list command shadowing builtin

- homeassistant_cli/cli.py
- homeassistant_cli/plugins/area.py
- homeassistant_cli/plugins/device.py
- homeassistant_cli/plugins/entity.py
- homeassistant_cli/plugins/event.py
- homeassistant_cli/plugins/map.py
- homeassistant_cli/plugins/raw.py
- homeassistant_cli/plugins/service.py
- homeassistant_cli/plugins/state.py
Click has deprecated the parameter name `autocompletion` in favor of the new name `shell_complete` as of version 8.1.0. From the [changelog](https://click.palletsprojects.com/en/8.1.x/changes/#version-8-1-0), we have
> `autocompletion` parameter to Command is renamed to `shell_complete`.
This caused issue #384, which is also reported in #382.
This PR implements the change in parameter name to stay compatible with click.
> fix: #384 #382 change deprecated parameter name autocompletion

- setup.py
The [`tabulate` package](https://pypi.org/project/tabulate/) has released version 0.9. This version is excluded with a preemptive upper bound:
https://github.com/home-assistant-ecosystem/home-assistant-cli/blob/341c45491c8b126f1db2b5f70b820d2821e4aec9/setup.py#L92
Based on the upstream [release notes](https://github.com/astanin/python-tabulate/blob/v0.9.0/CHANGELOG):
```
- 0.9.0: Drop support for Python 2.7, 3.5, 3.6.
Migrate to pyproject.toml project layout (PEP 621).
New output formats: `asciidoc`, various `*grid` and `*outline` formats.
New output features: vertical row alignment, separating lines.
New input format: list of dataclasses (Python 3.7 or later).
Support infinite iterables as row indices.
Improve column width options.
Improve support for ANSI escape sequences and document …
```
> Allow later tabulate
